[Feature][Brandon] Migrate secrets manager from notion to github
symphco/engineering-standards pull request #11
Opened 2024-06-12 09:51 UTC by bjlflores

2024-06-12 09:51 UTC, symphdevtools commented
Hi! I'm generating PR title and description for you and will automatically apply it to your PR. I'll react :rocket: to this comment when done. Just sit back and chill!

When you have new changes to this PR and you want to regenerate the title and PR description, just comment `churva`!

Let me know if something is not working well, e.g.:
- Some parts of the title and description weren't preserved when generating title and description
- Disappearing screenshots or links
- Etc.

Thanks!

(RIP hatdog)

2024-06-18 06:56 UTC, JHNLWHD requested changes

2024-06-18 06:56 UTC, JHNLWHD commented on standards/cloud_defaults.md
> +  - [**Cloud Build Secret Manager**](architecture/gcp_secret_manager/secret_manager_cloud_build.md)
I think it's App ENgine with Cloud Build? @bjlflores 

To make it more clear, update all references then we're good

2024-06-18 07:16 UTC, JHNLWHD approved these changes
LGTM 👍🏼

2024-06-18 07:19 UTC, merged