[Feature][Tin] add api, backend, and db naming standards
symphco/engineering-standards pull request #12
Opened 2024-06-19 10:37 UTC by christinejoymantua

2024-06-19 10:37 UTC, symphdevtools commented
Hi! I'm generating PR title and description for you and will automatically apply it to your PR. I'll react :rocket: to this comment when done. Just sit back and chill!

When you have new changes to this PR and you want to regenerate the title and PR description, just comment `churva`!

Let me know if something is not working well, e.g.:
- Some parts of the title and description weren't preserved when generating title and description
- Disappearing screenshots or links
- Etc.

Thanks!

(RIP hatdog)

2024-06-19 16:24 UTC, JHNLWHD requested changes

2024-06-19 16:24 UTC, JHNLWHD commented on standards/apis_backend_db_naming_standards.md
> +```
Let's also add via `@Entities('table_names')` as example

2024-06-20 06:53 UTC, johnreyev commented on standards/apis_backend_db_naming_standards.md
> +- **Database Columns** should be named in snake_case, which is all lowercase with underscores between words. For example, if you have a column for user email, it should be named 'user_email'.
```suggestion
- **Database Columns** should be named in snake_case, which is all lowercase with underscores between words. For example, if you have a column for user's email address, it should be named 'email_address'. 
```

2024-06-20 06:54 UTC, johnreyev commented on standards/apis_backend_db_naming_standards.md
> +- **API Functions** should be named in camelCase. For example, if you have a function that gets user data, it should be named 'getUserData'. If the function is for updating user roles, it should be n
```suggestion
- **API Functions** should be prefixed with verb and named in camelCase. For example, if you have a function that gets user data, it should be named 'getUserData'. If the function is for updating user roles, it should be named 'updateUserRoles'.
```

2024-06-20 08:10 UTC, JHNLWHD approved these changes
LGTM 👍🏼

2024-06-20 08:34 UTC, merged