[Feature][Tim] - Typescript standards
symphco/engineering-standards pull request #3
Opened 2024-04-12 06:14 UTC by timouano

- Typescript standards

2024-04-12 06:14 UTC, symphdevtools commented
Hi! I'm generating PR title and description for you and will automatically apply it to your PR. I'll react :rocket: to this comment when done. Just sit back and chill!

When you have new changes to this PR and you want to regenerate the title and PR description, just comment `churva`!

Let me know if something is not working well, e.g.:
- Some parts of the title and description weren't preserved when generating title and description
- Disappearing screenshots or links
- Etc.

Thanks!

(RIP hatdog)

2024-04-12 09:08 UTC, JHNLWHD requested changes
@timouano let's also add the `strict: true` rule in tsconfig to ensure and remind devs that their projects are using typescript

2024-04-12 09:08 UTC, JHNLWHD commented on standards/typescript_standards.md
> +```
@timouano let's confirm this, afaik we prefer `types` cc: @johnreyev @coderaven

2024-04-12 12:09 UTC, JHNLWHD commented on standards/typescript_standards.md
> +}
This is invalid syntax @timouano - it should be `type` - update all references

2024-04-15 11:15 UTC, JHNLWHD approved these changes
LGTM 👍🏼

2024-04-15 11:19 UTC, merged