[Feature][Trish] Added React Native standards
symphco/engineering-standards pull request #4
Opened 2024-04-12 06:19 UTC by tagadiadmt

2024-04-12 06:19 UTC, symphdevtools commented
Hi! I'm generating PR title and description for you and will automatically apply it to your PR. I'll react :rocket: to this comment when done. Just sit back and chill!

When you have new changes to this PR and you want to regenerate the title and PR description, just comment `churva`!

Let me know if something is not working well, e.g.:
- Some parts of the title and description weren't preserved when generating title and description
- Disappearing screenshots or links
- Etc.

Thanks!

(RIP hatdog)

2024-04-12 09:24 UTC, JHNLWHD requested changes

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +- **Component-Based Development**: Break down your UI into reusable components, each responsible for a specific piece of functionality or view. This approach promotes code reusability, maintainabilit
Let's confirm with our RN devs what do we follow, Is it atomic-based or feature-based?

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +- **State Management**: Keep state as localized as possible to avoid unnecessary re-renders and maintain a clear data flow.
Let's mention also global state management such as user data

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +- **Testing and Debugging**: Write comprehensive tests to ensure the reliability and stability of your React Native application.
Let's mention what testing library we prefer

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +- No nested components or getComponent inside render method. Always try to separate the components if possible.
Add sample codes

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +  > `CookieBanner.test.js`
Mention if we prefer a separate test folder or colocation

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +  > `fontsConfig.js`
Samples should be in `.ts`

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +- Use `.jsx` or `.tsx` extension a for React components
We prefer `.tsx`

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +  ```
Mention the specific eslint-config responsible for this, this should be automated

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +- To avoide the confusion about double quotes (" ") & single quotes (' '), use double quotes (" ") for JSX attributes and single quotes (' ') for the JS code
For this we can mention the eslint and prettier configs

2024-04-12 09:24 UTC, JHNLWHD commented on standards/react_native_standards.md
> +- Some cool crash analytics tools are `Sentry`, `Firebase`, `Crashlytics`, and more
Let's sync up with the team what's our default standard for this, I know it's Firebase Crashlytics

2024-06-27 03:59 UTC, JHNLWHD approved these changes
LGTM 👍🏼

2024-06-27 05:18 UTC, merged