[Feat][Geoff] Added cloud architecture guidelines
symphco/engineering-standards pull request #6
Opened 2024-05-09 20:08 UTC by diazGeoff

- Added guidelines for the ff:
  - Cloud IAM
  - Secret Manager

2024-05-09 20:09 UTC, symphdevtools commented
Hi! I'm generating PR title and description for you and will automatically apply it to your PR. I'll react :rocket: to this comment when done. Just sit back and chill!

When you have new changes to this PR and you want to regenerate the title and PR description, just comment `churva`!

Let me know if something is not working well, e.g.:
- Some parts of the title and description weren't preserved when generating title and description
- Disappearing screenshots or links
- Etc.

Thanks!

(RIP hatdog)

2024-05-10 03:38 UTC, JHNLWHD requested changes

2024-05-10 03:38 UTC, JHNLWHD commented on standards/cloud_defaults.md
> +The following standards outline the recommended configurations and practices for cloud-based services to ensure optimal security, scalability, and efficiency in line with industry best practices.
@diazGeoff let's add the diagram given by @rmarfil3 here so it serves as a visual guide for our cloud defaults

2024-05-10 03:38 UTC, JHNLWHD commented on standards/architecture/secret_manager.md
> +7. At the very bottom, click **DEPLOY**. This will deploy a new revision of your app with the environment variables loaded before your container is instantiated.
Can we add a GIF also?

2024-05-10 03:38 UTC, JHNLWHD commented on standards/architecture/cloud_iam.md
> +    ![Sample Output](./assets/iam_role.png)
Can we add a GIF also?

2024-05-10 13:51 UTC, JHNLWHD approved these changes
LGTM 👍🏼

2024-05-14 09:47 UTC, ramidem commented on standards/architecture/assets/iam_02.gif
is this public? ok lang makita email mo?

2024-05-14 10:14 UTC, merged